name: trip_planning_app
description: Trip planning project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.1
  intl_phone_field: ^3.1.0
  pinput: ^2.2.12
  intl: ^0.17.0
  flutter_svg: ^1.1.4
  google_maps_flutter: ^2.1.12
  # flutter_reorderable_list: ^1.2.0
  # boardview: ^0.2.2
  # vs_scrollbar: ^0.2.1
  drag_and_drop_lists: ^0.3.3
  flutter_form_builder: ^7.6.0
  form_builder_validators: ^8.1.1
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.6
  logger: ^1.1.0
  provider: ^6.0.3
  flutter_riverpod: ^1.0.4
  shimmer_animation: ^2.1.0+1
  tuple: ^2.0.0
  lottie: ^1.4.2
  loader_overlay: ^2.0.10
  flutter_spinkit: ^5.1.0
  upgrader: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google_logo.png
    - assets/animations/create_trip_loader.json
    - assets/images/login_banner.svg
    - assets/images/login_banner_2.svg